import turtle
s = turtle.Screen()

t = turtle.Turtle()
s.bgcolor( "pink" )

#drawing gambar
t.fillcolor("yellow")
t.begin_fill()
for i in range (6):
    t.left(90)
    t.forward(180)
    t.right(45)
    t.forward(30)
    t.right(45)
    t.forward(180)
    t.right(45)
    t.forward(30)
    t.right(45)
    t.forward(180)
    t.right(45)
    t.forward(30)
    t.right(45)
    t.forward(180)
    t.right(45)
    t.forward(30)
    t.right(45)
    t.end_fill()
    t.forward(120)
    t.right(90)
    t.penup()
    t.forward(120)
    t.pendown()
    t.circle(-45,360)
    t.right(90)
    t.penup()
    t.forward(100)
    t.pendown()
    t.forward(30)
    t.right(180)
    t.forward(15)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(15)
    t.right(180)
    t.forward(30)
    t.right(180)
    t.forward(15)
    t.left(90)
    t.penup()
    t.forward(15)
    t.pendown()
    t.right(90)
    t.forward(15)
    t.right(180)
    t.forward(30)
    t.right(180)
    t.forward(15)
    t.right(280)
    t.penup()
    t.forward(15)
    t.pendown()




    turtle.done()